# Generated by Django 5.2.4 on 2025-07-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('createdDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('index', models.PositiveIntegerField()),
                ('createdDatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('createdDatetime', models.DateTimeField()),
                ('task_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.taskstate')),
            ],
        ),
    ]
