# Generated by Django 5.2.4 on 2025-07-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='board',
            field=models.ForeignKey(default='5ebea30f-7656-4bbb-8176-f7d5e9812b51', on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
