# Generated by Django 5.2.4 on 2025-07-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_taskstate_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='createdDatetime',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdDatetime',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='taskstate',
            old_name='createdDatetime',
            new_name='created_datetime',
        ),
    ]
