# Generated by Django 5.2.4 on 2025-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_created_datetime_alter_board_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
