# Generated by Django 5.2.4 on 2025-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_taskstate_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
